#!/usr/bin/env python3
"""env-ownership.py — two owners, one precedence, and a migration that fails closed.

The behaviour under test is the split of the historical `~/.config/ailocal/.env`,
which held ailocal's generated secrets, the user's provider keys, flags from a
retired shell installer, and ten variables nothing read — with an all-or-nothing
writer whose only offer was "Re-generate .env? Existing values are lost."

What must be true afterwards:

    generated state  +  user overrides  =  effective environment

and the migration that gets an existing machine there must never rotate a key,
never print a secret, and never delete its own source before the destination is
proved good. Every test runs against tmp roots via AILOCAL_CONFIG / AILOCAL_STATE.
"""

from __future__ import annotations

import os
import stat
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

FAILS: list[str] = []

#: Stand-ins with the shape of the real values and none of the meaning. A test
#: fixture must never carry a value that was ever live on a real machine.
OLD_KEY = "sk-" + "a1" * 24
OLD_SEARX = "b2" * 32

LEGACY = f"""# ailocal — generated by `ailocal install`. Do NOT commit.
AILOCAL_ENV=local
HOST_HTTP_PORT=8080
OLLAMA_URL=http://host.docker.internal:11434
OLLAMA_QUANTIZATION=q4_K_M
POSTGRES_USER=ailocal
POSTGRES_PASSWORD=obsolete-postgres-password
POSTGRES_DB=ailocal
REDIS_PASSWORD=obsolete-redis-password
LITELLM_MASTER_KEY={OLD_KEY}
JWT_SECRET=obsolete-jwt-secret
ADMIN_PASSWORD=obsolete-admin-password
ENABLE_CLOUD=false
ANTHROPIC_API_KEY=
OPENAI_API_KEY=sk-user-openai-key
SEARXNG_SECRET={OLD_SEARX}
AILOCAL_TOOL_GATEWAY=filter
AILOCAL_SESSION_LEDGER=/app/captures/sessions
AILOCAL_TASK_NEGOTIATION=on
AILOCAL_TRACE_DIR=/app/captures/traces
AILOCAL_TOOL_GATEWAY_CAPTURE=
BRAVE_API=user-brave-key
"""


def check(cond: bool, label: str) -> None:
    print(f"  {'✓' if cond else '✗'} {label}")
    if not cond:
        FAILS.append(label)


def mode(p: Path) -> int:
    return stat.S_IMODE(p.stat().st_mode)


class Roots:
    """A throwaway machine: its own config root, state root and legacy file."""

    def __init__(self, legacy: str | None = LEGACY):
        self.tmp = tempfile.TemporaryDirectory()
        base = Path(self.tmp.name)
        self.config = base / "config"
        self.state = base / "state"
        self.config.mkdir(parents=True)
        self.state.mkdir(parents=True)
        os.environ["AILOCAL_CONFIG"] = str(self.config)
        os.environ["AILOCAL_STATE"] = str(self.state)
        if legacy is not None:
            (self.config / ".env").write_text(legacy)
            (self.config / ".env").chmod(0o600)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.tmp.cleanup()
        os.environ.pop("AILOCAL_CONFIG", None)
        os.environ.pop("AILOCAL_STATE", None)


def env():
    from ailocal import environment
    return environment


# ── the migration ───────────────────────────────────────────────────────────

def test_migration_classifies_every_variable() -> None:
    e = env()
    with Roots() as r:
        e.migrate()
        gen = e.parse(r.state / "env")
        user = e.parse(r.config / ".env.local")

        check(gen.get("LITELLM_MASTER_KEY") == OLD_KEY,
              "the generated master key survives byte-for-byte")
        check(gen.get("SEARXNG_SECRET") == OLD_SEARX,
              "the generated SearXNG secret survives byte-for-byte")
        check(sorted(gen) == sorted(e.GENERATED),
              "the generated file holds NOTHING but generated secrets")

        check(user.get("OPENAI_API_KEY") == "sk-user-openai-key"
              and user.get("BRAVE_API") == "user-brave-key",
              "user provider keys move to the user file")
        check("ANTHROPIC_API_KEY" in user and user["ANTHROPIC_API_KEY"] == "",
              "an intentionally empty provider key stays present and empty")
        check(user.get("AILOCAL_TOOL_GATEWAY") == "filter"
              and user.get("AILOCAL_TASK_NEGOTIATION") == "on",
              "non-default legacy flags are kept as user policy, not dropped")
        check("AILOCAL_TOOL_GATEWAY_CAPTURE" not in user and "OLLAMA_URL" not in user,
              "values equal to the code default are not persisted")

        both = set(gen) | set(user)
        check(not (both & set(e.DEAD)),
              "no variable with zero consumers is carried into either owner")
        for orphan in ("POSTGRES_PASSWORD", "REDIS_PASSWORD",
                       "JWT_SECRET", "ADMIN_PASSWORD"):
            check(orphan not in both, f"obsolete credential {orphan} is not migrated")

        check(not (r.config / ".env").exists(),
              "the mixed legacy file is retired once migration succeeds")
        check(mode(r.state / "env") == 0o600 and mode(r.config / ".env.local") == 0o600,
              "both owners are 0600")


def test_orphaned_credentials_survive_only_in_the_backup() -> None:
    """Deleting a secret with no record is not reversible; keeping it in live
    state is the problem being fixed. It goes to exactly one bounded place."""
    e = env()
    with Roots() as r:
        e.migrate()
        backups = list((r.state / "backups").glob("env-migration-*/.env"))
        check(len(backups) == 1, "exactly one bounded backup is written")
        text = backups[0].read_text()
        check("POSTGRES_PASSWORD=obsolete-postgres-password" in text,
              "the backup captures the obsolete credentials verbatim")
        check(mode(backups[0]) == 0o600, "the backup is 0600")
        live = (r.state / "env").read_text() + (r.config / ".env.local").read_text()
        check("obsolete-postgres-password" not in live
              and "obsolete-jwt-secret" not in live,
              "no obsolete credential value appears in live state")


def test_migration_is_idempotent_and_never_rotates() -> None:
    e = env()
    with Roots() as r:
        e.migrate()
        first_gen = (r.state / "env").read_text()
        first_user = (r.config / ".env.local").read_text()

        check(e.needs_migration() is False, "a migrated machine reports nothing to do")
        e.migrate()
        e.ensure()
        e.ensure()
        check((r.state / "env").read_text() == first_gen,
              "generated state is a fixed point across repeated runs")
        check((r.config / ".env.local").read_text() == first_user,
              "the user file is never rewritten by a second install")
        check(e.value("LITELLM_MASTER_KEY") == OLD_KEY,
              "the master key cannot be rotated by re-running the migration")


def test_a_fresh_machine_generates_and_a_second_install_does_not() -> None:
    e = env()
    with Roots(legacy=None) as r:
        e.ensure()
        key = e.value("LITELLM_MASTER_KEY")
        check(key.startswith("sk-") and len(key) > 20, "a fresh install generates a key")
        check(e.value("SEARXNG_SECRET") != "", "a fresh install generates a SearXNG secret")
        check(e.parse(r.config / ".env.local").get("ANTHROPIC_API_KEY") == "",
              "a fresh user file lists the provider keys, empty")
        e.ensure()
        check(e.value("LITELLM_MASTER_KEY") == key,
              "a second install reuses the existing key")


def test_missing_user_keys_are_not_an_error() -> None:
    e = env()
    with Roots(legacy="LITELLM_MASTER_KEY=%s\nSEARXNG_SECRET=%s\n" % (OLD_KEY, OLD_SEARX)) as r:
        e.migrate()
        user = e.parse(r.config / ".env.local")
        check(all(k in user for k in e.USER_ALWAYS),
              "a legacy file with no user keys still yields a complete user file")
        check(all(user[k] == "" for k in ("ANTHROPIC_API_KEY", "OPENAI_API_KEY", "BRAVE_API")),
              "absent provider keys become empty, not absent")
        check(e.value("LITELLM_MASTER_KEY") == OLD_KEY, "the key still survives")


def test_migration_fails_closed_without_deleting_the_source() -> None:
    """The failure that must never happen quietly: a half-migrated machine whose
    source is already gone has no master key and no way back to one."""
    e = env()
    with Roots() as r:
        real_write = e._write

        def sabotage(path, header, values):
            # Lose the user's keys on the way out — the shape of a partial write.
            if path == e.user_file():
                values = {k: v for k, v in values.items() if k != "OPENAI_API_KEY"}
            return real_write(path, header, values)

        e._write = sabotage
        try:
            e.migrate()
            check(False, "a lossy migration raises rather than reporting success")
        except SystemExit as exc:
            check("OPENAI_API_KEY" in str(exc),
                  "the failure names what did not survive")
        finally:
            e._write = real_write
        check((r.config / ".env").is_file(),
              "the legacy source is still there after a failed migration")
        check(e.parse(r.config / ".env")["OPENAI_API_KEY"] == "sk-user-openai-key",
              "the legacy source is unmodified")
        check(bool(list((r.state / "backups").glob("env-migration-*/.env"))),
              "the backup was taken before anything was written")


# ── precedence ──────────────────────────────────────────────────────────────

def test_user_overrides_generated_state() -> None:
    e = env()
    with Roots(legacy=None) as r:
        e.ensure()
        (r.state / "env").write_text(
            f"LITELLM_MASTER_KEY={OLD_KEY}\nSEARXNG_SECRET={OLD_SEARX}\nOLLAMA_URL=generated\n")
        check(e.value("OLLAMA_URL") == "generated", "generated state is read when nothing overrides")
        (r.config / ".env.local").write_text("OLLAMA_URL=http://ollama.example:11434\n")
        check(e.value("OLLAMA_URL") == "http://ollama.example:11434",
              "the user file wins over generated state")
        files = [p.name for p in e.env_files()]
        check(files == ["env", ".env.local"],
              "compose loads generated first and user second, so the user wins there too")


def test_the_key_projection_is_retired() -> None:
    """`~/.config/ailocal/env` held a second copy of the master key under a
    different name. A projection is not an authority."""
    e = env()
    with Roots() as r:
        (r.config / "env").write_text(
            f"AILOCAL_BASE_URL=http://127.0.0.1:4000\nAILOCAL_API_KEY={OLD_KEY}\n")
        e.migrate()
        check(not (r.config / "env").exists(), "migration removes the key projection")
        check(e.value("LITELLM_MASTER_KEY") == OLD_KEY,
              "the canonical key is unaffected by removing its projection")


def test_uninstall_surface_is_generated_state_only() -> None:
    """Whatever a teardown removes, the user's file is not ailocal's to delete
    and the two must be separable without reading either."""
    e = env()
    with Roots() as r:
        e.migrate()
        gen, user = e.generated_file(), e.user_file()
        check(r.state in gen.parents, "generated secrets live under the state root")
        check(r.config in user.parents, "user secrets live under the config root")
        check(gen != user and not str(gen).startswith(str(user)),
              "neither owner is nested inside the other")


def main() -> int:
    for fn in (test_migration_classifies_every_variable,
               test_orphaned_credentials_survive_only_in_the_backup,
               test_migration_is_idempotent_and_never_rotates,
               test_a_fresh_machine_generates_and_a_second_install_does_not,
               test_missing_user_keys_are_not_an_error,
               test_migration_fails_closed_without_deleting_the_source,
               test_user_overrides_generated_state,
               test_the_key_projection_is_retired,
               test_uninstall_surface_is_generated_state_only):
        print(f"\n{fn.__name__}")
        try:
            fn()
        except Exception as exc:  # noqa: BLE001
            FAILS.append(f"{fn.__name__} raised {exc!r}")
            print(f"  ✗ {fn.__name__} raised {exc!r}")
    print(f"\n{'FAILED: ' + str(len(FAILS)) if FAILS else 'PASS'}")
    for f in FAILS:
        print(f"  - {f}")
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
