#!/usr/bin/env python3
"""environment.py — who owns each environment variable, and where it lives.

ONE FILE USED TO HOLD FOUR OWNERS. `~/.config/ailocal/.env` mixed secrets
ailocal generated from `os.urandom` with API keys only a human can supply, plus
flags from an installer that no longer exists, plus values nothing reads. The
writer's only choice was all-or-nothing:

    if env_file.is_file():
        if assume_yes or not _yes("Re-generate .env? Existing values are lost."):

so an upgrade could never add a generated value without destroying the user's
provider keys, and in practice never added one at all. The file drifted from the
template for a year and nothing could tell which was which.

    ~/.config/ailocal/.env.local      USER-OWNED     provider keys, overrides
    ~/.local/state/ailocal/env        AILOCAL-OWNED  generated secrets

Both 0600. The split follows the roots ailocal already declares (policy.py):
config_root is user-editable policy, state_root is generated state. A key made
by `os.urandom` is state, whatever the historical filename said.

    generated state  +  user overrides  =  effective environment

User wins, always — that is what makes an override an override. Nothing else may
read either file directly: `value()` is the one reader, so the precedence exists
in one place and cannot be half-implemented by a second caller.

WHAT IS NOT PERSISTED. A default belongs in code. `OLLAMA_URL` is defaulted by
compose, so it appears in the user file only when the user actually differs from
it; `AILOCAL_ENV` was written by the template and read by nothing at all.
Rewriting those into a new file would carry the accumulation problem across the
migration and call it a fresh start.
"""
from __future__ import annotations

import os
import re
import shutil
import time
from pathlib import Path

from . import policy

#: Generated by ailocal, from os.urandom. NEVER rotated by a migration or an
#: upgrade: the value is embedded in generated client configs, so a rotation
#: nobody asked for silently breaks every configured client at once.
GENERATED = ("LITELLM_MASTER_KEY", "SEARXNG_SECRET")

#: Always present in the user file, even when empty. An empty provider key is a
#: STATEMENT — "I am not using the cloud" — and the renderers already treat it
#: as one (SearXNG disables the Brave engine rather than failing). Dropping the
#: line would turn that statement back into a question at every upgrade.
USER_ALWAYS = ("ANTHROPIC_API_KEY", "OPENAI_API_KEY", "BRAVE_API", "ENABLE_CLOUD")

#: User overrides of a value the code already defaults. Written ONLY when the
#: user's value differs from the default, so the file states differences and
#: nothing else. The defaults live where the consumer reads them — compose
#: interpolation — and are repeated here to decide "is this a difference?".
USER_OVERRIDE_DEFAULTS = {
    "OLLAMA_URL": "http://host.docker.internal:11434",
    "AILOCAL_TOOL_GATEWAY": "off",
    "AILOCAL_TASK_NEGOTIATION": "off",
    "AILOCAL_TOOL_GATEWAY_CAPTURE": "",
}

#: Zero consumers anywhere outside docs/, verified by grep over the source tree.
#: Six carry live secret VALUES for Postgres, Redis and an admin/JWT pair —
#: services ailocal does not run and has no code to start. Migrating them would
#: promote demonstrably obsolete secrets into permanently supported state, so
#: they are captured in the pre-migration backup and then removed.
DEAD = (
    "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB", "REDIS_PASSWORD",
    "JWT_SECRET", "ADMIN_PASSWORD",
    "HOST_HTTP_PORT", "OLLAMA_QUANTIZATION", "AILOCAL_SESSION_LEDGER",
    "AILOCAL_TRACE_DIR", "AILOCAL_ENV",
)

_LINE = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$")


# ── the four paths ──────────────────────────────────────────────────────────

def generated_file() -> Path:
    return policy.state_root() / "env"


def user_file() -> Path:
    return policy.config_root() / ".env.local"


def legacy_file() -> Path:
    """The mixed file this module replaces."""
    return policy.config_root() / ".env"


def legacy_projection() -> Path:
    """`ailocal clients` used to write AILOCAL_API_KEY here — a second copy of
    the master key, free to disagree with the canonical one after any rotation.
    A projection is not an authority; consumers read the owner instead."""
    return policy.config_root() / "env"


# ── reading ─────────────────────────────────────────────────────────────────

def parse(path: Path) -> dict[str, str]:
    """Names to values, comments and blanks dropped, ONE layer of quotes off."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = _LINE.match(line)
        if not m:
            continue
        v = m.group(2).strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            v = v[1:-1]
        out[m.group(1)] = v
    return out


def value(name: str) -> str:
    """The effective value: user override, else generated, else empty.

    THE one reader. A caller that opened a file itself would implement half of
    this precedence and be right until the day someone set an override.
    """
    user = parse(user_file())
    if name in user:
        return user[name]
    gen = parse(generated_file())
    if name in gen:
        return gen[name]
    # A machine that has not migrated yet still answers correctly.
    return parse(legacy_file()).get(name, "")


def env_files() -> list[Path]:
    """The files a consumer must load, IN ORDER, later winning."""
    return [p for p in (generated_file(), user_file()) if p.is_file()]


# ── writing ─────────────────────────────────────────────────────────────────

def _write(path: Path, header: str, values: dict[str, str]) -> None:
    """Atomic, 0600, parent 0700. Never partially visible to a reader."""
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        path.parent.chmod(0o700)
    except OSError:
        pass                                   # a shared parent we do not own
    body = header + "".join(f"{k}={v}\n" for k, v in values.items())
    tmp = path.with_name(path.name + ".incoming")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(body)
        os.replace(tmp, path)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    path.chmod(0o600)


_GENERATED_HEADER = """\
# ailocal — GENERATED STATE. Do not edit; do not commit; do not copy.
#
# Secrets ailocal made for this machine. They are regenerated only when absent,
# never on upgrade: the master key is embedded in every generated client config,
# so rotating it here would break all of them at once and say nothing.
#
# Your own keys and overrides go in the USER file, which wins over this one:
#   {user}
"""

_USER_HEADER = """\
# ailocal — YOURS. ailocal reads this file and never rewrites your values.
#
# It is loaded AFTER generated state, so anything here overrides it.
# Permissions are 0600; do not commit it.
#
# Provider keys are listed even when empty — an empty key means "not using this
# provider", and ailocal treats it as that rather than as a broken install.
# ENABLE_CLOUD is currently documentation only: no code reads it. Setting it
# true additionally requires uncommenting the matching model block in the
# generated litellm config.
#
# Overrides below this point exist only where you differ from the default.
"""


def ensure_generated() -> dict[str, str]:
    """Create the generated file if absent; otherwise leave it byte-for-byte.

    Returns the effective generated values. Idempotent by construction — the
    only branch that produces a new secret is the one where none exists.
    """
    path = generated_file()
    current = parse(path)
    if all(current.get(k) for k in GENERATED):
        return current
    made = dict(current)
    if not made.get("LITELLM_MASTER_KEY"):
        made["LITELLM_MASTER_KEY"] = "sk-" + os.urandom(24).hex()
    if not made.get("SEARXNG_SECRET"):
        # SearXNG refuses to start without a real secret.
        made["SEARXNG_SECRET"] = os.urandom(32).hex()
    _write(path, _GENERATED_HEADER.format(user=user_file()),
           {k: made[k] for k in GENERATED})
    return parse(path)


def ensure_user() -> dict[str, str]:
    """Create the user file if absent, with the provider keys empty.

    Never rewrites an existing one. This file is the user's; ailocal's whole
    claim on it is that it exists and is 0600.
    """
    path = user_file()
    if path.is_file():
        path.chmod(0o600)
        return parse(path)
    _write(path, _USER_HEADER, {k: "false" if k == "ENABLE_CLOUD" else ""
                                for k in USER_ALWAYS})
    return parse(path)


def ensure() -> None:
    """Both owners exist, with correct modes. Safe to call on every install."""
    ensure_generated()
    ensure_user()


# ── migration ───────────────────────────────────────────────────────────────

def _backup(src: Path) -> Path:
    """ONE bounded, timestamped copy under state, 0600. The only place the dead
    credentials survive — captured because deleting a secret with no record is
    not reversible, bounded because keeping them forever is the problem."""
    root = policy.state_root() / "backups"
    dest = root / f"env-migration-{time.strftime('%Y%m%d-%H%M%S')}"
    dest.mkdir(parents=True, exist_ok=True)
    root.chmod(0o700)
    dest.chmod(0o700)
    out = dest / src.name
    shutil.copyfile(src, out)
    out.chmod(0o600)
    for old in sorted(root.iterdir(), reverse=True)[3:]:
        shutil.rmtree(old, ignore_errors=True)
    return out


def needs_migration() -> bool:
    return legacy_file().is_file() or legacy_projection().is_file()


def migrate() -> list[str]:
    """Split the legacy mixed file into its two real owners.

    FAILS CLOSED: the legacy file is deleted only after both new files are on
    disk AND read back carrying every value that had to survive. A partial
    migration that had already deleted its own source would leave a machine with
    no master key and no way to recover one — the containers would come up with
    a key nothing else knows.

    Idempotent: a machine with no legacy file has nothing to do, and one that
    already migrated finds its generated secrets present and does not rotate.
    """
    actions: list[str] = []
    legacy = legacy_file()
    if not legacy.is_file():
        if legacy_projection().is_file():
            legacy_projection().unlink()
            actions.append(f"removed the derived key projection {legacy_projection()}")
        return actions

    old = parse(legacy)
    backup = _backup(legacy)
    actions.append(f"backed up the legacy environment to {backup} (0600)")

    # 1. generated secrets — REUSED, never re-rolled.
    gen = dict(parse(generated_file()))
    for k in GENERATED:
        if not gen.get(k) and old.get(k):
            gen[k] = old[k]
    keep_generated = {k: gen[k] for k in GENERATED if gen.get(k)}
    made = [k for k in GENERATED if not keep_generated.get(k)]
    if keep_generated:
        _write(generated_file(), _GENERATED_HEADER.format(user=user_file()),
               keep_generated)
    ensure_generated()                        # fills anything genuinely absent
    if made:
        actions.append(f"generated {', '.join(made)} (absent from the legacy file)")
    actions.append(f"carried {len(keep_generated)} generated secret(s) forward "
                   f"unchanged into {generated_file()}")

    # 2. user values. Provider keys always; overrides only where they differ
    # from the default the code already applies.
    user = dict(parse(user_file()))
    for k in USER_ALWAYS:
        user.setdefault(k, old.get(k, "false" if k == "ENABLE_CLOUD" else ""))
    kept_overrides = []
    for k, default in USER_OVERRIDE_DEFAULTS.items():
        if k in old and old[k] != default and k not in user:
            user[k] = old[k]
            kept_overrides.append(f"{k}={old[k]}")
    ordered = {k: user[k] for k in USER_ALWAYS if k in user}
    ordered.update({k: v for k, v in user.items() if k not in USER_ALWAYS})
    _write(user_file(), _USER_HEADER, ordered)
    actions.append(f"wrote {len(ordered)} user-owned value(s) to {user_file()} (0600)")
    if kept_overrides:
        actions.append("kept non-default override(s): " + ", ".join(kept_overrides))
    at_default = [k for k in USER_OVERRIDE_DEFAULTS
                  if k in old and old[k] == USER_OVERRIDE_DEFAULTS[k]]
    if at_default:
        actions.append("dropped value(s) equal to the code default: "
                       + ", ".join(at_default))

    # 3. VERIFY BEFORE DELETING. Nothing that had to survive may be missing.
    back_gen, back_user = parse(generated_file()), parse(user_file())
    required = {k: old[k] for k in GENERATED if old.get(k)}
    required.update({k: old[k] for k in USER_ALWAYS if k in old})
    missing = [k for k, v in required.items()
               if back_user.get(k, back_gen.get(k)) != v]
    if missing:
        raise SystemExit(
            "  ✗ environment migration incomplete — "
            f"{len(missing)} value(s) did not survive: {', '.join(sorted(missing))}\n"
            f"    Nothing was deleted. Your original file is untouched at {legacy}\n"
            f"    and backed up at {backup}.")

    # 4. only now retire the legacy owners.
    dropped = [k for k in DEAD if k in old]
    legacy.unlink()
    actions.append(f"retired the mixed legacy file {legacy}")
    if dropped:
        actions.append(f"dropped {len(dropped)} value(s) with no consumer "
                       f"(kept only in the backup): {', '.join(dropped)}")
    if legacy_projection().is_file():
        legacy_projection().unlink()
        actions.append(f"removed the derived key projection {legacy_projection()}")
    return actions
