#!/usr/bin/env bash
# security.sh — container supply-chain posture for the images ailocal runs.
#
# Answers four questions that a vulnerability scanner alone does not:
#
#   1. Is every declared image pinned to an immutable digest? A `latest` or
#      `main-stable` tag is not a pin. Both floated under us during the audit
#      that produced this script: `main-stable` moved 1.92.0 -> 1.93.0 while the
#      docs still claimed 1.92.0, and `searxng:latest` was rebuilt mid-session.
#   2. Does the RUNNING image match the DECLARED one? They diverge silently —
#      editing a compose file does not restart a container, so a repo can look
#      patched while the old image keeps serving.
#   3. Are the services bound to loopback? Reachability is what turns a package
#      finding into an exposure, and it is not visible to a scanner.
#   4. What does Docker Scout report? Optional: Scout needs auth and network, so
#      its absence degrades the report rather than failing it.
#
# Exit: 0 = pinned, no drift.  1 = a real problem (drift, or a floating pin).
#       2 = degraded (could not check something, e.g. Docker or Scout absent).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCAN=0; CHECK_UPDATES=0; SCHEDULE=
for a in "$@"; do case "$a" in
  --scan)           SCAN=1 ;;
  --check-updates)  CHECK_UPDATES=1 ;;
  --install-schedule)   SCHEDULE=install ;;
  --uninstall-schedule) SCHEDULE=uninstall ;;
  -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
  *) echo "unknown argument: $a" >&2; exit 2 ;;
esac; done

fail=0; degraded=0; update_available=0

# ── optional weekly check (OFF unless explicitly installed) ─────────────────
# ONE scheduler, not two. ailocal owns the LaunchAgent; it invokes each product's
# OWN check, so Cadence keeps ownership of the Qdrant logic while the machine
# gets a single weekly wakeup instead of two overlapping ones.
#
# It never upgrades anything. It writes state under XDG_STATE_HOME and notifies
# only when a check reports action required (exit 1). launchd gives a process no
# interactive shell and a minimal PATH, so every executable is resolved absolutely
# at install time -- a PATH assumption is why agents like this usually fail silently.
LABEL="com.ailocal.update-check"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
STATE="${AILOCAL_STATE:-$(python3 "$REPO/lib/profile-config" state-root)}"

if [[ -n "$SCHEDULE" ]]; then
  if [[ "$SCHEDULE" == uninstall ]]; then
    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
    rm -f "$PLIST"
    echo "weekly update check removed ($LABEL)"; exit 0
  fi
  mkdir -p "$STATE" "$HOME/Library/LaunchAgents"
  RUNNER="$STATE/update-check.sh"
  cat > "$RUNNER" <<RUNNER_EOF
#!/bin/bash
# Generated by 'ailocal security --install-schedule'. Reports only; upgrades nothing.
exec >"$STATE/update-check.log" 2>&1
echo "=== \$(date -u +%FT%TZ) ==="
rc=0
"$REPO/lib/security.sh" --check-updates || rc=\$?
CAD="$(cd "$REPO/.." && pwd)/cadence/scripts/cadence"
if [ -x "\$CAD" ]; then "\$CAD" security --check-updates || rc=\$?; fi
echo "\$(date -u +%FT%TZ) rc=\$rc" > "$STATE/update-check.status"
# Notify ONLY when action is required. A quiet check must stay quiet.
if [ "\$rc" = 1 ]; then
  /usr/bin/osascript -e 'display notification "A container update is available for review. Run: ailocal security --check-updates" with title "ailocal"' 2>/dev/null || true
fi
exit 0
RUNNER_EOF
  chmod +x "$RUNNER"
  cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array>
    <string>/bin/bash</string><string>$RUNNER</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict><key>Weekday</key><integer>1</integer><key>Hour</key><integer>10</integer><key>Minute</key><integer>0</integer></dict>
  <key>RunAtLoad</key><false/>
  <key>EnvironmentVariables</key><dict>
    <key>PATH</key><string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict></plist>
PLIST_EOF
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || true
  echo "weekly update check installed (Mondays 10:00, reports only, upgrades nothing)"
  echo "  state:  $STATE/update-check.status"
  echo "  remove: ailocal security --uninstall-schedule"
  exit 0
fi

ok()   { printf '  \033[32mPASS\033[0m  %s\n' "$1"; }
bad()  { printf '  \033[31mFAIL\033[0m  %s\n' "$1"; fail=1; }
warn() { printf '  \033[33mWARN\033[0m  %s\n' "$1"; degraded=1; }
head_() { printf '\n\033[1m%s\033[0m\n' "$1"; }

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not installed — cannot assess container posture."; exit 2
fi

# ── 1. every declared image is pinned by digest ─────────────────────────────
head_ "DECLARED IMAGES"
declared=()
while IFS= read -r line; do
  img="${line#*image:}"; img="$(echo "$img" | tr -d ' ')"
  [[ -z "$img" || "$img" == \$* ]] && continue
  declared+=("$img")
  if [[ "$img" == *"@sha256:"* ]]; then
    ok "pinned by digest: ${img%%@*}"
  else
    bad "NOT pinned (floating tag): $img"
  fi
done < <(grep -rh '^\s*image:' "$REPO"/deploy/*/compose.yaml 2>/dev/null || true)
[[ ${#declared[@]} -eq 0 ]] && warn "no images declared under deploy/*/compose.yaml"

# ── 2. running digest matches declared digest ───────────────────────────────
head_ "DECLARED vs RUNNING"
for img in "${declared[@]}"; do
  [[ "$img" != *"@sha256:"* ]] && continue
  repo="${img%%@*}"; repo="${repo%%:*}"; want="${img##*@}"
  cid="$(docker ps -q --filter "ancestor=$img" 2>/dev/null | head -1)"
  if [[ -z "$cid" ]]; then
    # Fall back to matching by repository, which catches the drift case: a
    # container running the SAME repo at a DIFFERENT digest is the failure
    # this check exists for, and an ancestor filter would simply miss it.
    cid="$(docker ps -q 2>/dev/null | while read -r c; do
             ri="$(docker inspect "$c" --format '{{.Config.Image}}' 2>/dev/null)"
             [[ "$ri" == "$repo"* ]] && echo "$c" && break
           done | head -1)"
  fi
  if [[ -z "$cid" ]]; then
    warn "$repo: not running (cannot compare)"; continue
  fi
  name="$(docker inspect "$cid" --format '{{.Name}}' | tr -d /)"
  got="$(docker inspect "$(docker inspect "$cid" --format '{{.Image}}')" \
          --format '{{range .RepoDigests}}{{.}} {{end}}' 2>/dev/null | tr ' ' '\n' | grep "^$repo@" | head -1)"
  got="${got##*@}"
  if [[ -z "$got" ]]; then
    warn "$name: running image has no repo digest (built locally?)"
  elif [[ "$got" == "$want" ]]; then
    ok "$name runs the declared digest (${want:7:12})"
  else
    bad "$name DRIFT — declared ${want:7:12}, running ${got:7:12}. Run 'ailocal start'."
  fi
done

# ── 3. reachability ─────────────────────────────────────────────────────────
# A finding in a package is only an exposure if something can reach it. Every
# ailocal service is loopback-only by policy; this asserts it rather than
# trusting the compose file to still say so.
head_ "REACHABILITY"
while read -r cid; do
  [[ -z "$cid" ]] && continue
  name="$(docker inspect "$cid" --format '{{.Name}}' | tr -d /)"
  ports="$(docker port "$cid" 2>/dev/null || true)"
  [[ -z "$ports" ]] && { ok "$name publishes no ports"; continue; }
  exposed="$(echo "$ports" | awk '{print $3}' | grep -v '^127\.0\.0\.1:' | grep -v '^\[::1\]:' || true)"
  if [[ -z "$exposed" ]]; then
    ok "$name bound to loopback only"
  else
    bad "$name reachable off-host: $(echo "$exposed" | tr '\n' ' ')"
  fi
done < <(docker ps -q 2>/dev/null)

# ── 4. optional scan ────────────────────────────────────────────────────────
if [[ $SCAN -eq 1 ]]; then
  head_ "SCOUT (fixable critical/high)"
  if ! docker scout version >/dev/null 2>&1; then
    warn "docker scout unavailable — no vulnerability data"
  else
    for img in "${declared[@]}"; do
      out="$(docker scout cves --only-fixed --only-severity critical,high "$img" 2>&1 || true)"
      if echo "$out" | grep -q "No vulnerable package detected"; then
        ok "${img%%@*}: no fixable critical/high"
      else
        n="$(echo "$out" | grep -cE '^ *[0-9]+C +[0-9]+H' || true)"
        warn "${img%%@*}: $n package(s) with fixable critical/high — see docs/security.md"
      fi
    done
  fi
else
  head_ "SCOUT"
  echo "  skipped — re-run with --scan (needs network and a Docker login)"
fi

# ── 4b. provenance ──────────────────────────────────────────────────────────
# A digest proves the bytes did not change; it does NOT prove who published them.
# cosign closes that gap where a publisher signs. Missing cosign DEGRADES the
# report (exit 2) rather than failing it, and is never auto-installed -- adding a
# verification tool to a machine is the operator's decision, not this script's.
head_ "PROVENANCE"
if ! command -v cosign >/dev/null 2>&1; then
  warn "cosign not installed — signatures cannot be verified"
  echo "      the installer provisions it; this machine predates that or removed it"
  echo "      install:  brew install cosign"
  echo "      then:     ailocal security   (re-runs verification)"
else
  for img in "${declared[@]}"; do
    repo="${img%%@*}"; repo="${repo%%:*}"
    # Keyless/OIDC signatures need the publisher's identity; a bare `cosign
    # verify` without one is not a meaningful assertion, so an image whose
    # publisher documents no method is reported as such rather than "unsigned".
    # `cosign tree` QUERIES THE REGISTRY. `cosign triangulate` does not -- it only
    # computes the expected .sig tag name from the digest, so it succeeds for
    # unsigned images too. It reported a signature for SearXNG, which publishes
    # none. Deprecated in cosign 3.x as well. Do not use it to prove existence.
    out="$(timeout 60 cosign tree "$img" 2>&1 || true)"
    if echo "$out" | grep -q "No Supply Chain Security Related Artifacts"; then
      warn "$repo: publisher signs nothing for this digest — provenance unverifiable"
    elif echo "$out" | grep -q "Signatures for an image"; then
      # Presence is not validity. A real assertion needs the publisher's identity
      # (keyless OIDC) or key, which upstream does not document for these images;
      # reporting "signature present" is the honest ceiling here.
      ok "$repo: signature published for this digest (identity policy not configured)"
    else
      warn "$repo: could not determine signature status"
    fi
  done
fi

# ── 5. update availability ──────────────────────────────────────────────────
# Discovery ONLY. This never pulls a candidate over a running service and never
# rewrites a pin: a newer tag existing is not a reason to replace a validated
# image. It reports, and a human decides. ailocal owns LiteLLM and SearXNG;
# Qdrant belongs to Cadence and is deliberately not checked here.
if [[ $CHECK_UPDATES -eq 1 ]]; then
  head_ "UPDATE AVAILABILITY"

  # Resolve a tag to a digest WITHOUT pulling the image.
  remote_digest() {
    { docker buildx imagetools inspect "$1" --format '{{.Manifest.Digest}}' 2>/dev/null \
      || docker manifest inspect "$1" 2>/dev/null | sed -n 's/.*"digest": "\(sha256:[a-f0-9]*\)".*/\1/p' | head -1
    } || true
  }
  json_get() { python3 -c "import json,sys;d=json.load(sys.stdin);print($1)" 2>/dev/null || true; }

  for img in "${declared[@]}"; do
    repo="${img%%@*}"; repo="${repo%%:*}"; cur="${img##*@}"
    case "$repo" in
      ghcr.io/berriai/litellm)
        # `|| true` is load-bearing: under `set -e` a failed curl inside $() aborted
        # the whole script with curl's own exit code (7), so an offline machine got
        # a crash instead of the documented "degraded" result. stderr is silenced
        # for the same reason -- a connection error is a status here, not output.
        newest="$(curl -fsSL --max-time 20 https://api.github.com/repos/BerriAI/litellm/releases/latest 2>/dev/null \
                  | json_get "d['tag_name']" || true)"
        cand_ref="ghcr.io/berriai/litellm:${newest}" ;;
      searxng/searxng)
        # SearXNG ships rolling `latest` rather than semver releases, so the
        # candidate IS latest -- which is exactly why it must stay digest-pinned.
        newest="latest"; cand_ref="searxng/searxng:latest" ;;
      *) warn "$repo: no upstream discovery strategy defined"; continue ;;
    esac

    if [[ -z "$newest" ]]; then
      warn "$repo: could not reach upstream (offline?) — update status unknown"; continue
    fi
    cand="$(remote_digest "$cand_ref")"
    if [[ -z "$cand" ]]; then
      warn "$repo: found $newest but could not resolve its digest"; continue
    fi

    # Digest inequality alone does NOT mean "behind". The LiteLLM pin tracks
    # main-stable, which runs AHEAD of the newest tagged GitHub release: comparing
    # digests only, this check proposed v1.94.0 as an "update" to the 1.94.1 we
    # already run -- a downgrade. Compare VERSIONS where a version is knowable.
    cfg_ver=""
    [[ "$repo" == ghcr.io/berriai/litellm ]] && \
      cfg_ver="$(grep -hoE 'AILOCAL_LITELLM_VERSION=[0-9.]+' "$REPO"/deploy/litellm/compose.yaml 2>/dev/null | head -1 | cut -d= -f2)"
    printf '  %s\n' "$repo"
    printf '      configured  %s%s\n' "${cur:7:19}" "${cfg_ver:+  ($cfg_ver)}"
    printf '      newest      %s  (%s)\n' "${cand:7:19}" "$newest"
    if [[ -n "$cfg_ver" && "$newest" =~ ^v?[0-9] ]]; then
      up_ver="${newest#v}"
      # Sort both; if the configured version is the greater-or-equal one, we are current.
      if [[ "$(printf '%s\n%s\n' "$cfg_ver" "$up_ver" | sort -V | tail -1)" == "$cfg_ver" ]]; then
        ok "$repo is current ($cfg_ver, at or ahead of newest release $newest)"
        continue
      fi
    fi
    if [[ "$cand" == "$cur" ]]; then
      ok "$repo is current ($newest)"
    else
      update_available=1
      printf '      \033[33mUPDATE AVAILABLE\033[0m — %s\n' "$newest"
      printf '      review:  docker scout cves --only-fixed --only-severity critical,high %s\n' "$cand_ref"
      printf '      apply:   edit the digest in deploy/*/compose.yaml, then\n'
      printf '               ailocal start && lib/test-all.sh --full && ailocal security\n'
      printf '      rollback: restore the previous digest and re-run ailocal start\n'
    fi
  done
fi

echo
# A newer release is NOT a failure. Exit 1 is reserved for a real defect (drift
# or a floating pin); an available update is reported as its own status so a
# scheduled check can distinguish "act now" from "something is broken".
if [[ $fail -ne 0 ]]; then
  echo "SECURITY: problems found"; exit 1
elif [[ $degraded -ne 0 ]]; then
  echo "SECURITY: pinned and loopback-only; some checks degraded"; exit 2
elif [[ $update_available -ne 0 ]]; then
  echo "SECURITY: pinned and healthy — an upstream update is available for review"; exit 1
fi
echo "SECURITY: all images pinned, no drift, loopback-only"
