#!/usr/bin/env python3
"""test-claude-instructions.py — the composed Claude Code instruction file.

`~/.config/ailocal/claude` is a separate CLAUDE_CONFIG_DIR. It does NOT inherit
`~/.claude/CLAUDE.md`, so the shared engineering policy has to be DEPLOYED into
it rather than referenced. That is why the deployed file is composed from two
in-repo sources instead of being a thin overlay.

The failure this guards against is drift back to a hand-maintained file: the
previous version accumulated a stale context figure, a hard-coded backend table
that no longer matched the profile, and a filesystem-first search rule that
contradicted the repository-intelligence order. Those are asserted ABSENT here,
by string, so re-introducing one fails the gate.

Runs entirely against the repo and temporary directories. It never reads or
writes the real HOME.

Usage: python3 scripts/test-claude-instructions.py
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED = ROOT / "config/clients/CLAUDE.md"
SOURCES = [
    ROOT / "config/clients/claude/instructions/00-engineering-policy.md",
    ROOT / "config/clients/claude/instructions/10-ailocal-overlay.md",
]

fails = 0


def check(cond, name):
    global fails
    print(f"  {'PASS' if cond else 'FAIL'}  {name}")
    if not cond:
        fails += 1


def sync():
    return subprocess.run([str(ROOT / "scripts/sync-models.sh")],
                          cwd=ROOT, capture_output=True, text=True)


print("SOURCES")
for p in SOURCES:
    check(p.exists(), f"source present: {p.relative_to(ROOT)}")
check(not any("Generated by ailocal" in p.read_text() for p in SOURCES),
      "sources are hand-written — no generated header leaked into them")

print("\nGENERATION")
r = sync()
check(r.returncode == 0, "sync-models.sh exits clean")
check("clients/CLAUDE.md (composed)" in r.stdout, "sync reports composing CLAUDE.md")
text = GENERATED.read_text()

check(text.startswith("<!-- Generated by ailocal"), "generated-ownership header is first")
check("Do not edit this file or its deployed copy." in text, "header forbids editing")
for p in SOURCES:
    check(str(p.relative_to(ROOT)) in text.splitlines()[0],
          f"header names its source: {p.name}")

print("\nPLACEHOLDERS ARE FILLED, NOT LEFT BEHIND")
check("<!-- ailocal:capabilities -->" not in text, "capability placeholder substituted")
check("<!-- ailocal:claude-slots -->" not in text, "slot placeholder substituted")
check("`ailocal-architecture`" in text and "`ailocal-implementation`" in text,
      "canonical capability names are present")
check("| `claude-opus-*` |" in text, "compat-alias table is generated from clients.yaml")

print("\nREQUIRED CONTENT")
required = [
    ("Native LSP", "repository-intelligence ladder names native LSP first"),
    ("grepai", "the ladder names the repository index"),
    ("no-silent-fallback", "no-silent-fallback rule is referenced by name"),
    ("disclose the failure", "fallback requires disclosing the failure"),
    ("http://localhost:4000", "local proxy endpoint"),
    ("health/liveliness", "health check command"),
    ("./scripts/start.sh", "correct restart command"),
    ("CLAUDE_CONFIG_DIR=~/.config/ailocal/claude", "states which config root this is"),
    ("inherits nothing from it", "states that it does not inherit ~/.claude"),
    ("[UNVERIFIED]", "provenance labels are defined for use"),
    ("127.0.0.1", "bind-address security rule"),
    ("Authorization: Bearer", "model listing uses the authenticated form"),
]
for needle, label in required:
    check(needle in text, label)

print("\nREMOVED CONTENT (regressions, asserted absent by string)")
forbidden = [
    ("reach first for `rg`", "filesystem-first search rule"),
    ("16–32K", "stale context-window figure"),
    ("16-32K", "stale context-window figure (ascii hyphen)"),
    ("No cloud API calls are made", "unconditional no-network claim"),
    ("next best tool without fuss", "silent-fallback permission"),
    ("don't drive from them", "architecture/review subagent-only restriction"),
    ("Frontend guidance", "frontend design guidance"),
    ("50-70 lines", "arbitrary output-length cap"),
    ("The filesystem is your ground truth", "filesystem-first investigation rule"),
    ("qwen2.5-coder:14b)", "hard-coded backend inside prose"),
]
for needle, label in forbidden:
    check(needle not in text, f"absent: {label}")

print("\nIDEMPOTENCE")
before = GENERATED.read_bytes()
sync()
check(GENERATED.read_bytes() == before, "a second sync is byte-identical")

print("\nDEPLOYMENT INTO A CLEAN ROOT (temp HOME — the real one is never touched)")
# install-clients.sh requires .env (written by install.sh). Without it the
# installer exits before deploying anything, so the deployment assertions would
# fail for a reason that has nothing to do with this file. Say so and skip,
# rather than reporting a red that misdirects.
if not (ROOT / ".env").exists():
    print("  SKIP  .env absent — installer cannot run; deployment checks not executed")
    print("        (run ./scripts/install.sh first for full coverage)")
    print()
    print("CLAUDE INSTRUCTION TESTS: OK (deployment section skipped)"
          if not fails else f"CLAUDE INSTRUCTION TESTS: {fails} FAILED")
    sys.exit(1 if fails else 0)

with tempfile.TemporaryDirectory() as tmp:
    tmp = Path(tmp)
    env = dict(os.environ, HOME=str(tmp / "home"), XDG_CONFIG_HOME=str(tmp / "cfg"))
    (tmp / "home").mkdir()
    claude_root = tmp / "cfg" / "ailocal" / "claude"

    r = subprocess.run([str(ROOT / "scripts/install-clients.sh"), "claude"],
                       cwd=ROOT, env=env, capture_output=True, text=True)
    check(r.returncode == 0,
          f"install-clients.sh claude exits clean (rc={r.returncode})")
    if r.returncode != 0:
        print("    installer output (last lines):")
        for line in (r.stdout + r.stderr).strip().splitlines()[-5:]:
            print(f"      {line}")
    deployed = claude_root / "CLAUDE.md"
    check(deployed.exists(), "clean install creates the config root and CLAUDE.md")
    check(deployed.read_bytes() == GENERATED.read_bytes(),
          "deployed copy is byte-identical to the generated file")
    check(str(Path.home()) not in str(claude_root), "test wrote only under a temp root")

    # Repair: a stale deployed file must be REPLACED, not merged or backed up
    # into place. The old file is what carried the drift, so treating it as a
    # source is exactly the bug being fixed.
    deployed.write_text("# stale\nreach first for `rg`\n")
    user_owned = claude_root / "agents" / "cadence-overlay.md"
    user_owned.parent.mkdir(parents=True, exist_ok=True)
    user_owned.write_text("user content\n")

    subprocess.run([str(ROOT / "scripts/install-clients.sh"), "claude"],
                   cwd=ROOT, env=env, capture_output=True, text=True)
    check(deployed.read_bytes() == GENERATED.read_bytes(),
          "repair replaces a stale generated file wholesale")
    check("reach first" not in deployed.read_text(), "no stale content survives repair")
    check(user_owned.exists() and user_owned.read_text() == "user content\n",
          "a file ailocal does not own is left untouched")

    # Re-run idempotence at the deployed layer.
    d1 = deployed.read_bytes()
    subprocess.run([str(ROOT / "scripts/install-clients.sh"), "claude"],
                   cwd=ROOT, env=env, capture_output=True, text=True)
    check(deployed.read_bytes() == d1, "a second install changes nothing")

print()
if fails:
    print(f"CLAUDE INSTRUCTION TESTS: {fails} FAILED")
    sys.exit(1)
print("CLAUDE INSTRUCTION TESTS: OK")
